server:
  port: 8001
spring:
  application:
    name: cloud-hystrix-payment-service


eureka:
  client:
    #表示是否入驻eureka服务器
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

